# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
# created-by: conda 24.9.2
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2025.2.25-h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.40-h12ee557_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran5-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2025a-h04d1e81_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-11.2.0-h00389a5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgomp-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/_openmp_mutex-5.1-1_gnu.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h5eee18b_6.conda
https://repo.anaconda.com/pkgs/main/linux-64/c-ares-1.19.1-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/expat-2.6.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gmp-6.3.0-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/icu-73.1-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9e-h5eee18b_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/lerc-4.0.0-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libabseil-20240116.2-cxx17_h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libdeflate-1.22-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libev-4.33-h7f8727e_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.4.4-h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libiconv-1.16-h5eee18b_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/libsodium-1.0.18-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.41.5-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libuv-1.48.0-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-base-1.3.2-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxcb-1.15-h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.4-h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-3.0.15-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/sleef-3.5.1-h5eee18b_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/tbb-2021.8.0-hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.6.4-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.13-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2023.1.0-hdb19cb5_46306.conda
https://repo.anaconda.com/pkgs/main/linux-64/libcups-2.4.2-h2d74bed_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20230828-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libnghttp2-1.57.0-h2d74bed_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.39-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libprotobuf-4.25.3-he621ea3_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libssh2-1.11.1-h251f7ec_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxml2-2.13.5-hfdd30dd_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpfr-4.2.1-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pcre2-10.42-hebb0a14_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.14-h39e8969_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xcb-util-cursor-0.1.4-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zeromq-4.3.5-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.5.6-hc292b87_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.12.1-h4a9f257_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/krb5-1.20.1-h143b758_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libglib-2.78.4-hdc74915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.5.1-hffd6297_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxkbcommon-1.0.1-h097e994_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2023.1.0-h213fc3f_46344.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpc-1.3.1-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.45.3-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cyrus-sasl-2.1.28-h52b45da_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/fontconfig-2.14.1-h55d465d_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/lcms2-2.16-hb9589c4_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libcurl-8.12.1-hc9e6f67_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openjpeg-2.5.2-he7f1fd0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.12.9-h5148396_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotli-python-1.0.9-py312h6a678d5_9.conda
https://repo.anaconda.com/pkgs/main/noarch/cycler-0.11.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/debugpy-1.8.11-py312h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-5.1.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/executing-0.8.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/filelock-3.13.1-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/fsspec-2024.12.0-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gmpy2-2.2.1-py312h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/joblib-1.4.2-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.4.8-py312h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-3.0.2-py312h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.4.0-py312h5eee18b_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpmath-1.3.0-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mysql-8.4.0-h29a9f33_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/nest-asyncio-1.6.0-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/networkx-3.4.2-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openldap-2.6.4-h42fbc30_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/packaging-24.2-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/parso-0.8.4-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pillow-11.1.0-py312hcea889d_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/platformdirs-3.10.0-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/psutil-5.9.0-py312h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/noarch/ptyprocess-0.7.0-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pure_eval-0.2.2-pyhd3eb1b0_0.conda
https://conda.anaconda.org/anaconda/noarch/pycparser-2.21-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pygments-2.15.1-py312h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyparsing-3.2.0-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyqt6-sip-13.9.1-py312h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-tzdata-2023.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pytz-2024.1-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyzmq-26.2.0-py312h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-72.1.0-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/threadpoolctl-3.5.0-py312he106c6f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.4.2-py312h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/traitlets-5.14.3-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/typing_extensions-4.12.2-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/unicodedata2-15.1.0-py312h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.2.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.45.1-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wrapt-1.17.0-py312h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zipp-3.21.0-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/asttokens-2.0.5-pyhd3eb1b0_0.conda
https://conda.anaconda.org/anaconda/linux-64/cffi-1.17.1-py312h1fdaa30_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/comm-0.2.1-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/deprecated-1.2.13-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/fonttools-4.55.3-py312h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/importlib-metadata-7.0.1-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jedi-0.19.2-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jinja2-3.1.5-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jupyter_core-5.7.2-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpq-17.2-hdbd6064_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtorch-2.5.1-cpu_mkl_h75fa98c_102.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-inline-0.1.6-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-2.2.2-py312h0da6c21_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pexpect-4.8.0-pyhd3eb1b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-25.0-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/prompt-toolkit-3.0.43-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-dateutil-2.9.0post0-py312h06a4308_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/sip-6.10.0-py312h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/sympy-1.13.3-py312h06a4308_1.conda
https://conda.anaconda.org/anaconda/linux-64/cryptography-43.0.3-py312h7825ff9_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jupyter_client-8.6.3-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/opentelemetry-api-1.26.0-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/prompt_toolkit-3.0.43-hd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/qtbase-6.7.2-hdaa5aa8_1.conda
https://repo.anaconda.com/pkgs/main/noarch/stack_data-0.2.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ipython-8.30.0-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/qtsvg-6.7.2-he621ea3_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ipykernel-6.29.5-py312h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/qtdeclarative-6.7.2-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/qttools-6.7.2-h80c7b02_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/qtwebchannel-6.7.2-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/qtwebsockets-6.7.2-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyqt-6.7.1-py312h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/bottleneck-1.4.2-py312ha883a20_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/contourpy-1.3.1-py312hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-3.10.0-py312h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-base-3.10.0-py312hbfdbfaf_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.3.11-py312h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.2.8-py312h526ad5a_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-2.2.2-py312hc5e2394_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numexpr-2.10.1-py312h3c60e43_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pytorch-2.5.1-cpu_mkl_py312h8bb77d7_102.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.15.1-py312hc5e2394_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandas-2.2.3-py312h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/scikit-learn-1.6.1-py312h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/seaborn-0.13.2-py312h06a4308_1.conda
