program: ogbn_graphs.py
name: run_${now:%Y-%m-%d_%H-%M-%S}
project: bachelorproject  # change this
entity: s224225-danmarks-tekniske-universitet-dtu"  # change this

metric:
    goal: maximize
    name: accuracy
parameters:
    walk_length:
        values: [5, 10, 15]
    num_walks:
        values: [10, 15, 20]
    epochs:
        values: [50, 100, 150]
    alpha:
        values: [-0.5, 0.5, 1.5]
run_cap: 10